{
"project_title": "Inteligentne szacowanie wystąpienia ryzyka arytmii",
"h1_credits": "Szacowanie wystąpienia ryzyka arytmii",
"h2_credits": "Kredyt",
"h1_login": "Ryzyko wystąpienia arytmii",
"h2_login": "Dostęp dla członków",
"h3_login": "Dostęp dla członków",
"login": "Zaloguj się",
"university": "University of Jaen",
"quiron": "Hospital Universitario QuirónSalud de Madrid",
"sas": "Complejo Hospitalario de Jaén y Linares",
"avs": "Hospital General Universitario de Elda",
"h1_menu": "ryzyko wystąpienia arytmii",
"ecg": "EKG",
"ecg_done": "Zapis EKG",
"patients": "Pacjenci",
"logout": "Wyloguj się",
"return": "powórt",
"h1_logout": "Wyloguj się",
"h2_logout": "Czy na pewno chcesz się wylogować?",
"accept": "OK",
"deny": "Anuluj",
"h1_record": "Zapis EKG",
"h2_record": "Zapis EKG",
"search": "Szukaj",
"dni": "Identyfikator",
"date": "Data",
"risklevel": "Poziom ryzyka",
"riskcontext": "czynniki ryzyka",
"actions": "wdroone postępowanie",
"years": "lat",
"male": "Mężczyzna",
"female": "Kobieta",
"action1": "Zwiększona częstotliwość EKG",
"action2": "Zmiejszona częstotliwość EKG",
"action3": "Przegląd leków",
"action4": "Czynność4",
"action5": "Czynność5",
"riskfactor1": "Inne niż 67",
"riskfactor2": "Kobieta",
"riskfactor3": "Moczopędny",
"riskfactor4": "Surowica",
"riskfactor5": "AMI",
"riskfactor6": "Sepsa",
"riskfactor7": "Lek wydłużający odstęp QT",
"riskfactor8": "Dwa lub więcej leków wydłużających odstęp QT",
"riskfactor9": "Kardiologiczny",
"tag_yes": "tak",
"tag_no": "nie",
"h1_patients": "Pacjenci",
"h2_patients": "Nowy/ aktualizacja pacjent",
"save": "Zapisz",
"name": "Imię",
"surname": "Nazwisko",
"birthday": "Data urodzenia",
"sex": "Płeć",
"iam_label": "AMI (ostry zawał mięśnia sercowego)",
"cardiac_label": "Zawał serca",
"remarks": "Uwagi",
"h1_ecg": "EKG",
"h2_ecg": "Szacowanie wystąpienia ryzyka arytmii",
"estimate": "Szacowanie",
"factors": "Czynniki",
"factor1": "Moczopędne ASA (furosemid, torasemid, bumetanid)",
"factor2": "Stężenie potasu w surowicy krwi (K+) <=3,5 mEq/L",
"factor3": "Sepsa",
"factor4": "Lek wydłuża odstęp QT",
"factor5": "Dwa lub więcej leków wydłużających odstęp QT",
"factors_legend": "Niski: 0-1,58 | Norma: 1,59 - 2,38 | Wysoki 2,39 - 5",
"risk": "Ryzyko",
"risk_label":  "Niezdefiniowany poziom czynników ",
"risk_string": "Poziom czynników ",
"risk_undefined": "niezdefiniowany /nieznany",
"risk_low": "niski",
"risk_average": "norma",
"risk_high": "wysoki",
"page": "strona",
"next": "Następna",
"prev": "Poprzednia",
"prep": " z ",
"iderror": "Nie ma danych dla tego pacjenta",
"notexist": "Pacjent nie istnieje",
"computing": "Szacowanie",
"qtcerror": "QTc nie może być obliczone!",
"link2menu": "Menu",
"fileerror": "Plik nie został wskazany",
"exterror": "Złe rozszeżenie",
"edit": "Edytować",
"basal_tx": "podstawowy",
"upfile1": "Dodaj obraz EKG",
"deletefile1": "Usuń obraz EKG",
"clipped": "Początkowe wycięcie",
"qtc_man": "Wprowadź wartość, jeśli jest dostępna",
"historial": "Historia pacjenta",
"actualiza": "Zaktualizuj obserwacje",
"number": "Numer",
"actualizaecg": "Zaktualizuj i wróć do historii"
}